input_features:
    - name: bone
      type: text
      fill_value: VRM_UNKNOWN_BONE
    - name: specification_version
      type: category
      fill_value: VRM_UNVERSIONED
    - name: bone_hierarchy
      type: text
      level: char
      preprocessing:
        max_sequence_length: 2048
    - name: bone_rest_x_global_origin_in_meters
      type: numerical
    - name: bone_rest_y_global_origin_in_meters
      type: numerical
    - name: bone_rest_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_x_global_origin_in_meters
      type: numerical
    - name: bone_y_global_origin_in_meters
      type: numerical
    - name: bone_z_global_origin_in_meters
      type: numerical

output_features:
    - name: label
      type: category
      top_k: 1
      fill_value: VRM_UNKNOWN_BONE

preprocessing:
  stratify: label
  text:
      most_common_word: 10000
      tokenizer: characters