input_features:
    - name: bone
      type: text
      level: char
      preprocessing:
        tokenizer: space
        max_sequence_length: 2048
        unknown_symbol: VRM_UNKNOWN_BONE
        fill_value: VRM_UNKNOWN_BONE
        missing_value_strategy: fill_with_mode
    - name: bone_hierarchy
      type: text
      level: char
      preprocessing:
        tokenizer: space
        max_sequence_length: 2048
        unknown_symbol: VRM_UNKNOWN_BONE
        fill_value: VRM_UNKNOWN_BONE
        missing_value_strategy: fill_with_const
    - name: vrm_fine_category
      type: category
      preprocessing:
        fill_value: VRM_FINE_CATEGORY_NONE
        missing_value_strategy: fill_with_const
    - name: bone_rest_x_global_origin_in_meters
      type: numerical
    - name: bone_rest_y_global_origin_in_meters
      type: numerical
    - name: bone_rest_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_rest_x_global_scale_in_meters
      type: numerical
    - name: bone_rest_y_global_scale_in_meters
      type: numerical
    - name: bone_rest_z_global_scale_in_meters
      type: numerical
    - name: bone_x_global_origin_in_meters
      type: numerical
    - name: bone_y_global_origin_in_meters
      type: numerical
    - name: bone_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_x_global_scale_in_meters
      type: numerical
    - name: bone_y_global_scale_in_meters
      type: numerical
    - name: bone_z_global_scale_in_meters
      type: numerical
    - name: bone_parent_x_global_origin_in_meters
      type: numerical
    - name: bone_parent_y_global_origin_in_meters
      type: numerical
    - name: bone_parent_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_parent_x_global_scale_in_meters
      type: numerical
    - name: bone_parent_y_global_scale_in_meters
      type: numerical
    - name: bone_parent_z_global_scale_in_meters
      type: numerical
output_features:
    - name: label
      type: category
      top_k: 1
      preprocessing:
        fill_value: VRM_UNKNOWN_BONE
        missing_value_strategy: fill_with_const
preprocessing:
  stratify: vrm_fine_category