input_features:
    - name: specification_version
      type: category
    - name: bone
      type: category
    - name: bone_hierarchy
      type: bag
    - name: bone_rest_x_global_origin_in_meters
      type: numerical
    - name: bone_rest_y_global_origin_in_meters
      type: numerical
    - name: bone_rest_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_rest_x_global_scale_in_meters
      type: numerical
    - name: bone_rest_y_global_scale_in_meters
      type: numerical
    - name: bone_rest_z_global_scale_in_meters
      type: numerical
    - name: bone_x_global_origin_in_meters
      type: numerical
    - name: bone_y_global_origin_in_meters
      type: numerical
    - name: bone_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_x_global_scale_in_meters
      type: numerical
    - name: bone_y_global_scale_in_meters
      type: numerical
    - name: bone_z_global_scale_in_meters
      type: numerical
    - name: bone_parent_x_global_origin_in_meters
      type: numerical
    - name: bone_parent_y_global_origin_in_meters
      type: numerical
    - name: bone_parent_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_parent_x_global_scale_in_meters
      type: numerical
    - name: bone_parent_y_global_scale_in_meters
      type: numerical
    - name: bone_parent_z_global_scale_in_meters
      type: numerical

output_features:
    - name: label
      type: text
