input_features:
    - name: bone
      type: text
      fill_value: VRM_UNKNOWN_BONE
      preprocessing:
        tokenizer: characters
        max_sequence_length: 2048
        fill_value: VRM_UNKNOWN_BONE
        missing_value_strategy: fill_with_const
    - name: bone_hierarchy
      type: text
      fill_value: ''
      preprocessing:
        tokenizer: characters
        max_sequence_length: 2048
        fill_value: ''
        missing_value_strategy: fill_with_const
    - name: bone_rest_x_global_origin_in_meters
      type: numerical
    - name: bone_rest_y_global_origin_in_meters
      type: numerical
    - name: bone_rest_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_rest_x_global_scale_in_meters
      type: numerical
    - name: bone_rest_y_global_scale_in_meters
      type: numerical
    - name: bone_rest_z_global_scale_in_meters
      type: numerical
    - name: bone_x_global_origin_in_meters
      type: numerical
    - name: bone_y_global_origin_in_meters
      type: numerical
    - name: bone_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_x_global_scale_in_meters
      type: numerical
    - name: bone_y_global_scale_in_meters
      type: numerical
    - name: bone_z_global_scale_in_meters
      type: numerical
    - name: bone_parent_x_global_origin_in_meters
      type: numerical
    - name: bone_parent_y_global_origin_in_meters
      type: numerical
    - name: bone_parent_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_parent_x_global_scale_in_meters
      type: numerical
    - name: bone_parent_y_global_scale_in_meters
      type: numerical
    - name: bone_parent_z_global_scale_in_meters
      type: numerical

output_features:
    - name: vrm_fine_category
      type: category
      flatten_inputs: true
      fill_value: VRM_FINE_CATEGORY_NONE
      preprocessing:
        fill_value: VRM_FINE_CATEGORY_NONE
        missing_value_strategy: fill_with_const
      num_fc_layers: 2
      fc_size: 64
    - name: label
      type: category
      top_k: 1
      fill_value: VRM_UNKNOWN_BONE
      preprocessing:
        fill_value: VRM_UNKNOWN_BONE
        missing_value_strategy: fill_with_const
      dependencies:
          - vrm_fine_category
      num_fc_layers: 1
      fc_size: 64
preprocessing:
  stratify: vrm_fine_category