input_features:
    - name: bone
      type: text
    - name: specification_version
      type: category
      top_k: 1
      fill_value: VRM_UNVERSIONED      
    - name: bone_hierarchy
      type: text
      level: char
    - name: bone_rest_x_global_origin_in_meters
      type: numerical
    - name: bone_rest_y_global_origin_in_meters
      type: numerical
    - name: bone_rest_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_x_global_origin_in_meters
      type: numerical
    - name: bone_y_global_origin_in_meters
      type: numerical
    - name: bone_z_global_origin_in_meters
      type: numerical

output_features:
    - name: label
      type: category
      top_k: 1
      fill_value: VRM_UNKNOWN_BONE