input_features:
    - name: label
      type: category
    - name: specification_version
      type: category
    - name: bone
      type: category
    - name: bone_hierarchy
      type: bag
    - name: bone_rest_x_global_origin_in_meters
      type: numerical
    - name: bone_rest_y_global_origin_in_meters
      type: numerical
    - name: bone_rest_z_global_origin_in_meters
      type: numerical
    - name: bone_rest_truncated_normalized_basis_axis_x_0
      type: numerical
    - name: bone_rest_truncated_normalized_basis_axis_x_1
      type: numerical
    - name: bone_rest_truncated_normalized_basis_axis_x_2
      type: numerical
    - name: bone_rest_truncated_normalized_basis_axis_y_0
      type: numerical
    - name: bone_rest_truncated_normalized_basis_axis_y_1
      type: numerical
    - name: bone_rest_truncated_normalized_basis_axis_y_2
      type: numerical
    - name: bone_rest_x_global_scale_in_meters
      type: numerical
    - name: bone_rest_y_global_scale_in_meters
      type: numerical
    - name: bone_rest_z_global_scale_in_meters
      type: numerical
    - name: bone_x_global_origin_in_meters
      type: numerical
    - name: bone_y_global_origin_in_meters
      type: numerical
    - name: bone_z_global_origin_in_meters
      type: numerical
    - name: bone_truncated_normalized_basis_axis_x_0
      type: numerical
    - name: bone_truncated_normalized_basis_axis_x_1
      type: numerical
    - name: bone_truncated_normalized_basis_axis_x_2
      type: numerical
    - name: bone_truncated_normalized_basis_axis_y_0
      type: numerical
    - name: bone_truncated_normalized_basis_axis_y_1
      type: numerical
    - name: bone_truncated_normalized_basis_axis_y_2
      type: numerical
    - name: bone_x_global_scale_in_meters
      type: numerical
    - name: bone_y_global_scale_in_meters
      type: numerical
    - name: bone_z_global_scale_in_meters
      type: numerical
    # - name: bone_parent_x_global_origin_in_meters
    #   type: numerical
    - name: bone_parent_y_global_origin_in_meters
      type: numerical
    - name: bone_parent_z_global_origin_in_meters
      type: numerical
    - name: bone_parent_truncated_normalized_basis_axis_x_0
      type: numerical
    - name: bone_parent_truncated_normalized_basis_axis_x_1
      type: numerical
    - name: bone_parent_truncated_normalized_basis_axis_x_2
      type: numerical
    - name: bone_parent_truncated_normalized_basis_axis_y_0
      type: numerical
    - name: bone_parent_truncated_normalized_basis_axis_y_1
      type: numerical
    - name: bone_parent_truncated_normalized_basis_axis_y_2
      type: numerical
    - name: bone_parent_x_global_scale_in_meters
      type: numerical
    - name: bone_parent_y_global_scale_in_meters
      type: numerical
    - name: bone_parent_z_global_scale_in_meters
      type: numerical

output_features:
    - name: label
      type: category
