input_features:
    - name: bone
      type: category
    - name: bone_hierarchy
      type: text
    - name: bone_rest_x_global_origin_in_meters
      type: numerical
    - name: bone_rest_y_global_origin_in_meters
      type: numerical
    - name: bone_rest_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_rest_x_global_scale_in_meters
      type: numerical
    - name: bone_rest_y_global_scale_in_meters
      type: numerical
    - name: bone_rest_z_global_scale_in_meters
      type: numerical
    - name: bone_x_global_origin_in_meters
      type: numerical
    - name: bone_y_global_origin_in_meters
      type: numerical
    - name: bone_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_x_global_scale_in_meters
      type: numerical
    - name: bone_y_global_scale_in_meters
      type: numerical
    - name: bone_z_global_scale_in_meters
      type: numerical
    - name: bone_parent_x_global_origin_in_meters
      type: numerical
    - name: bone_parent_y_global_origin_in_meters
      type: numerical
    - name: bone_parent_z_global_origin_in_meters
      type: numerical
      type: numerical
    - name: bone_parent_x_global_scale_in_meters
      type: numerical
    - name: bone_parent_y_global_scale_in_meters
      type: numerical
    - name: bone_parent_z_global_scale_in_meters
      type: numerical      
    - name: hips
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftUpperLeg
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightUpperLeg
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftLowerLeg
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightLowerLeg
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftFoot
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightFoot
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: spine
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: chest
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: neck
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: head
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftShoulder
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightShoulder
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftUpperArm
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightUpperArm
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftLowerArm
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightLowerArm
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftHand
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightHand
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftToes
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightToes
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftEye
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightEye
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftThumbProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftThumbIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftThumbDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftIndexProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftIndexIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftIndexDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftMiddleProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftMiddleIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftMiddleDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftRingProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftRingIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftRingDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftLittleProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftLittleIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: leftLittleDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightThumbProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightThumbIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightThumbDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightIndexProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightIndexIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightIndexDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightMiddleProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightMiddleIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightMiddleDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightRingProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightRingIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightRingDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightLittleProximal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightLittleIntermediate
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: rightLittleDistal
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
    - name: upperChest
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE

output_features:
    - name: label
      type: text
      preprocessing:
          unknown_symbol: VRM_UNKNOWN_BONE